import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { parsePackJson } from "../bin/lib/npm-pack.mjs";

// Relevant fields from npm 11.19.1 and 12.0.2 pack output.
const record = {
  name: "skills4sh",
  filename: "skills4sh-0.5.1.tgz",
  files: [{ path: "package.json", size: 740, mode: 420 }],
};

test("pack JSON accepts npm 11's single-record array", () => {
  assert.deepEqual(parsePackJson(JSON.stringify([record]), "npm pack"), record);
});

test("pack JSON accepts npm 12's package-name map", () => {
  assert.deepEqual(parsePackJson(JSON.stringify({ skills4sh: record }), "npm pack"), record);
  const scoped = { ...record, name: "@scope/demo", filename: "scope-demo-1.0.0.tgz" };
  assert.deepEqual(parsePackJson(JSON.stringify({ [scoped.name]: scoped }), "npm pack"), scoped);
});

test("pack JSON rejects malformed JSON with the command label", () => {
  assert.throws(() => parsePackJson("npm notice\n[]", "npm pack --dry-run"),
    /npm pack --dry-run did not emit JSON:/);
});

test("pack JSON rejects ambiguous, error, and incomplete results", () => {
  for (const value of [
    null, true, "output", 1, [], {}, [record, record],
    { skills4sh: record, other: { ...record, name: "other" } },
    { error: { code: "EPACK", summary: "pack failed" } },
    { other: record }, record,
    [null], [1], [{}], [{ ...record, name: "" }],
    [{ ...record, filename: undefined }], [{ ...record, filename: "" }],
    [{ ...record, files: undefined }], [{ ...record, files: {} }],
    [{ ...record, files: [null] }], [{ ...record, files: [{ path: 1 }] }],
  ]) {
    assert.throws(() => parsePackJson(JSON.stringify(value), "npm pack"),
      /npm pack returned unexpected JSON shape/, JSON.stringify(value));
  }
});

test("npm files allowlist excludes Python caches while keeping skill source", async () => {
  const dir = await packFixture();
  try {
    for (const path of ["skills/demo/assets/scripts/__pycache__/helper.pyc", "skills/demo/assets/scripts/helper.pyc"]) {
      await mkdir(dirname(join(dir, path)), { recursive: true });
      await writeFile(join(dir, path), "generated bytecode");
    }
    const packed = spawnSync("npm", ["pack", "--dry-run", "--json", "--ignore-scripts"], { cwd: dir, encoding: "utf8" });
    assert.equal(packed.status, 0, packed.stderr);
    const { files } = parsePackJson(packed.stdout, "npm pack --dry-run");
    assert.ok(files.some((file) => file.path === "skills/demo/SKILL.md"));
    assert.ok(files.some((file) => file.path === "skills/demo/assets/scripts/helper.py"));
    assert.equal(files.some((file) => file.path.includes("__pycache__") || file.path.endsWith(".pyc")), false);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("pack gate rejects absent or stale bundles and lockfile drift", async () => {
  const script = fileURLToPath(new URL("../bin/pack-check.mjs", import.meta.url));
  for (const scenario of ["valid", "missing", "stale", "lock-drift"]) {
    const dir = await packFixture();
    try {
      if (scenario === "missing") await rm(join(dir, "node_modules"), { recursive: true });
      if (scenario === "stale") {
        await writeFile(join(dir, "node_modules/undici/package.json"), JSON.stringify({ name: "undici", version: "6.27.0" }));
      }
      if (scenario === "lock-drift") {
        const lock = JSON.parse(await readFile(join(dir, "package-lock.json"), "utf8"));
        lock.packages["node_modules/undici"].version = "6.27.0";
        await writeFile(join(dir, "package-lock.json"), JSON.stringify(lock));
      }
      const result = spawnSync(process.execPath, [script], { cwd: dir, encoding: "utf8" });
      if (scenario === "valid") {
        assert.equal(result.status, 0, result.stderr);
        assert.match(result.stdout, /bundles undici@/);
      } else {
        assert.notEqual(result.status, 0, scenario);
        const expected = {
          missing: /run npm ci.*missing node_modules\/undici\/package.json/,
          stale: /packed undici must match the locked version/,
          "lock-drift": /package-lock.json.*must match package.json/,
        };
        assert.match(result.stderr, expected[scenario]);
      }
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  }
});

async function packFixture() {
  const dir = await mkdtemp(join(tmpdir(), "skills4sh-pack-fixture-"));
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
  delete pkg.scripts;
  const files = {
    "package.json": JSON.stringify(pkg),
    "package-lock.json": await readFile(new URL("../package-lock.json", import.meta.url), "utf8"),
    "skills-lock.json": "{}",
    "bin/install.mjs": "#!/usr/bin/env node\n",
    "skills/demo/SKILL.md": "# Demo\n",
    "skills/demo/assets/scripts/helper.py": "print('demo')\n",
    "node_modules/undici/package.json": JSON.stringify({ name: "undici", version: pkg.optionalDependencies.undici }),
    "node_modules/undici/index.js": "module.exports = {};\n",
    "node_modules/undici/LICENSE": "MIT\n",
  };
  for (const [path, content] of Object.entries(files)) {
    await mkdir(dirname(join(dir, path)), { recursive: true });
    await writeFile(join(dir, path), content);
  }
  return dir;
}
